-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\idek11\idek11.vhd
-- Created: 2026-04-06 22:57:37
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.6276e-09
-- Target subsystem base rate: 1.6276e-09
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1.6276e-09
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1_re                       ce_out        1.6276e-09
-- Out1_im                       ce_out        1.6276e-09
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: idek11
-- Source Path: idek11
-- Hierarchy Level: 0
-- Model version: 1.12
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.idek11_pkg.ALL;

ENTITY idek11 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out1_re                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        Out1_im                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END idek11;


ARCHITECTURE rtl OF idek11 IS

  -- Component Declarations
  COMPONENT IFFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26
          dataOut_im                      :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : IFFT
    USE ENTITY work.IFFT(rtl);

  -- Constants
  CONSTANT Direct_Lookup_Table_n_D_table_data : vector_of_unsigned16(0 TO 511) := 
    (to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#3FFF#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#3FFF#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16),
     to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16), to_unsigned(16#0000#, 16));  -- ufix16 [512]

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL count_step                       : unsigned(8 DOWNTO 0) := to_unsigned(16#000#, 9);  -- ufix9
  SIGNAL count_from                       : unsigned(8 DOWNTO 0) := to_unsigned(16#000#, 9);  -- ufix9
  SIGNAL HDL_Counter_out1                 : unsigned(8 DOWNTO 0) := to_unsigned(16#000#, 9);  -- ufix9
  SIGNAL count                            : unsigned(8 DOWNTO 0) := to_unsigned(16#000#, 9);  -- ufix9
  SIGNAL need_to_wrap                     : std_logic;
  SIGNAL count_value                      : unsigned(8 DOWNTO 0) := to_unsigned(16#000#, 9);  -- ufix9
  SIGNAL Direct_Lookup_Table_n_D_out1     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL IFFT_out1_re                     : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL IFFT_out1_im                     : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL IFFT_out1_re_signed              : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL IFFT_out1_im_signed              : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL Data_Type_Conversion_out1_re     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Data_Type_Conversion_out1_im     : signed(15 DOWNTO 0);  -- int16

BEGIN
  u_IFFT : IFFT
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => std_logic_vector(Direct_Lookup_Table_n_D_out1),  -- uint16
              validIn => Constant_out1,
              dataOut_re => IFFT_out1_re,  -- sfix26
              dataOut_im => IFFT_out1_im  -- sfix26
              );

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 511
  count_step <= to_unsigned(16#001#, 9);

  count_from <= to_unsigned(16#000#, 9);

  enb <= clk_enable;

  count <= HDL_Counter_out1 + count_step;

  
  need_to_wrap <= '1' WHEN HDL_Counter_out1 = to_unsigned(16#1FF#, 9) ELSE
      '0';

  
  count_value <= count WHEN need_to_wrap = '0' ELSE
      count_from;

  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= to_unsigned(16#000#, 9);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        HDL_Counter_out1 <= count_value;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  Direct_Lookup_Table_n_D_out1 <= Direct_Lookup_Table_n_D_table_data(to_integer(HDL_Counter_out1));

  Constant_out1 <= '1';

  IFFT_out1_re_signed <= signed(IFFT_out1_re);

  IFFT_out1_im_signed <= signed(IFFT_out1_im);

  Data_Type_Conversion_out1_re <= IFFT_out1_re_signed(15 DOWNTO 0);
  Data_Type_Conversion_out1_im <= IFFT_out1_im_signed(15 DOWNTO 0);

  Out1_re <= std_logic_vector(Data_Type_Conversion_out1_re);

  Out1_im <= std_logic_vector(Data_Type_Conversion_out1_im);

  ce_out <= clk_enable;

END rtl;

