-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\idek11\RADIX22FFT_SDF1_1.vhd
-- Created: 2026-04-09 21:29:06
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RADIX22FFT_SDF1_1
-- Source Path: idek11/IFFT/RADIX22FFT_SDF1_1
-- Hierarchy Level: 2
-- Model version: 1.13
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.idek11_pkg.ALL;

ENTITY RADIX22FFT_SDF1_1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        din_1_1_re_dly                    :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17
        din_1_1_im_dly                    :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17
        din_1_vld_dly                     :   IN    std_logic;
        rd_1_Addr                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        rd_1_Enb                          :   IN    std_logic;
        proc_1_enb                        :   IN    std_logic;
        dout_1_1_re                       :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18
        dout_1_1_im                       :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18
        dout_1_1_vld                      :   OUT   std_logic;
        dinXTwdl_1_1_vld                  :   OUT   std_logic
        );
END RADIX22FFT_SDF1_1;


ARCHITECTURE rtl OF RADIX22FFT_SDF1_1 IS

  -- Component Declarations
  COMPONENT SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          dout                            :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  COMPONENT SDFCommutator1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          din_1_vld_dly                   :   IN    std_logic;
          xf_re                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          xf_im                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          xf_vld                          :   IN    std_logic;
          dinXTwdlf_re                    :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          dinXTwdlf_im                    :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          dinxTwdlf_vld                   :   IN    std_logic;
          btf1_re                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          btf1_im                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          btf2_re                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          btf2_im                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
          btf_vld                         :   IN    std_logic;
          wrData_im                       :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18
          wrAddr                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          wrEnb                           :   OUT   std_logic;
          dout_1_1_re                     :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18
          dout_1_1_im                     :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18
          dout_1_1_vld                    :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SimpleDualPortRAM_generic
    USE ENTITY work.SimpleDualPortRAM_generic(rtl);

  FOR ALL : SDFCommutator1
    USE ENTITY work.SDFCommutator1(rtl);

  -- Signals
  SIGNAL din_1_1_re_dly_signed            : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL din_re                           : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL dinXTwdl_re                      : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL din_1_1_im_dly_signed            : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL din_im                           : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL dinXTwdl_im                      : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL dinXTwdl_1_1_vld_1               : std_logic;
  SIGNAL x_re                             : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL x_vld                            : std_logic;
  SIGNAL btf2_im                          : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL btf2_re                          : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL btf1_im                          : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL btf1_re                          : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL dinXTwdlf_im                     : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL dinXTwdlf_re                     : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL xf_im                            : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL wrData_im                        : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL wrAddr                           : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL wrEnb                            : std_logic;
  SIGNAL x_im                             : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL x_im_signed                      : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Radix22ButterflyG1_btf1_re_reg   : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL Radix22ButterflyG1_btf1_im_reg   : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL Radix22ButterflyG1_btf2_re_reg   : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL Radix22ButterflyG1_btf2_im_reg   : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL Radix22ButterflyG1_x_re_dly1     : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Radix22ButterflyG1_x_im_dly1     : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Radix22ButterflyG1_x_vld_dly1    : std_logic;
  SIGNAL Radix22ButterflyG1_dinXtwdl_re_dly1 : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Radix22ButterflyG1_dinXtwdl_im_dly1 : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Radix22ButterflyG1_dinXtwdl_re_dly2 : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Radix22ButterflyG1_dinXtwdl_im_dly2 : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Radix22ButterflyG1_dinXtwdl_vld_dly1 : std_logic;
  SIGNAL Radix22ButterflyG1_dinXtwdl_vld_dly2 : std_logic;
  SIGNAL xf_re                            : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL xf_vld                           : std_logic;
  SIGNAL dinxTwdlf_vld                    : std_logic;
  SIGNAL btf_vld                          : std_logic;
  SIGNAL dout_1_1_re_tmp                  : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL dout_1_1_im_tmp                  : std_logic_vector(17 DOWNTO 0);  -- ufix18

BEGIN
  u_dataMEM_im_0_1_generic : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 8,
                 DataWidth => 18
                 )
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => wrData_im,
              wr_addr => wrAddr,
              wr_en => wrEnb,
              rd_addr => rd_1_Addr,
              dout => x_im
              );

  u_SDFCOMMUTATOR_1 : SDFCommutator1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_1_vld_dly => din_1_vld_dly,
              xf_re => std_logic_vector(xf_re),  -- sfix18
              xf_im => std_logic_vector(xf_im),  -- sfix18
              xf_vld => xf_vld,
              dinXTwdlf_re => std_logic_vector(dinXTwdlf_re),  -- sfix18
              dinXTwdlf_im => std_logic_vector(dinXTwdlf_im),  -- sfix18
              dinxTwdlf_vld => dinxTwdlf_vld,
              btf1_re => std_logic_vector(btf1_re),  -- sfix18
              btf1_im => std_logic_vector(btf1_im),  -- sfix18
              btf2_re => std_logic_vector(btf2_re),  -- sfix18
              btf2_im => std_logic_vector(btf2_im),  -- sfix18
              btf_vld => btf_vld,
              wrData_im => wrData_im,  -- sfix18
              wrAddr => wrAddr,  -- ufix8
              wrEnb => wrEnb,
              dout_1_1_re => dout_1_1_re_tmp,  -- sfix18
              dout_1_1_im => dout_1_1_im_tmp,  -- sfix18
              dout_1_1_vld => dout_1_1_vld
              );

  din_1_1_re_dly_signed <= signed(din_1_1_re_dly);

  din_re <= resize(din_1_1_re_dly_signed, 18);

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinXTwdl_re <= to_signed(16#00000#, 18);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dinXTwdl_re <= din_re;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  din_1_1_im_dly_signed <= signed(din_1_1_im_dly);

  din_im <= resize(din_1_1_im_dly_signed, 18);

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinXTwdl_im <= to_signed(16#00000#, 18);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dinXTwdl_im <= din_im;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinXTwdl_1_1_vld_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dinXTwdl_1_1_vld_1 <= din_1_vld_dly;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  x_re <= to_signed(16#00000#, 18);

  intdelay_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_vld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_vld <= rd_1_Enb;
      END IF;
    END IF;
  END PROCESS intdelay_3_process;


  x_im_signed <= signed(x_im);

  -- Radix22ButterflyG1
  Radix22ButterflyG1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Radix22ButterflyG1_btf1_re_reg <= to_signed(16#00000#, 19);
      Radix22ButterflyG1_btf1_im_reg <= to_signed(16#00000#, 19);
      Radix22ButterflyG1_btf2_re_reg <= to_signed(16#00000#, 19);
      Radix22ButterflyG1_btf2_im_reg <= to_signed(16#00000#, 19);
      Radix22ButterflyG1_x_re_dly1 <= to_signed(16#00000#, 18);
      Radix22ButterflyG1_x_im_dly1 <= to_signed(16#00000#, 18);
      Radix22ButterflyG1_x_vld_dly1 <= '0';
      xf_re <= to_signed(16#00000#, 18);
      xf_im <= to_signed(16#00000#, 18);
      xf_vld <= '0';
      Radix22ButterflyG1_dinXtwdl_re_dly1 <= to_signed(16#00000#, 18);
      Radix22ButterflyG1_dinXtwdl_im_dly1 <= to_signed(16#00000#, 18);
      Radix22ButterflyG1_dinXtwdl_re_dly2 <= to_signed(16#00000#, 18);
      Radix22ButterflyG1_dinXtwdl_im_dly2 <= to_signed(16#00000#, 18);
      Radix22ButterflyG1_dinXtwdl_vld_dly1 <= '0';
      Radix22ButterflyG1_dinXtwdl_vld_dly2 <= '0';
      btf_vld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xf_re <= Radix22ButterflyG1_x_re_dly1;
        xf_im <= Radix22ButterflyG1_x_im_dly1;
        xf_vld <= Radix22ButterflyG1_x_vld_dly1;
        btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
        Radix22ButterflyG1_btf1_re_reg <= resize(Radix22ButterflyG1_x_re_dly1, 19) + resize(Radix22ButterflyG1_dinXtwdl_re_dly2, 19);
        Radix22ButterflyG1_btf2_re_reg <= resize(Radix22ButterflyG1_x_re_dly1, 19) - resize(Radix22ButterflyG1_dinXtwdl_re_dly2, 19);
        Radix22ButterflyG1_btf1_im_reg <= resize(Radix22ButterflyG1_x_im_dly1, 19) + resize(Radix22ButterflyG1_dinXtwdl_im_dly2, 19);
        Radix22ButterflyG1_btf2_im_reg <= resize(Radix22ButterflyG1_x_im_dly1, 19) - resize(Radix22ButterflyG1_dinXtwdl_im_dly2, 19);
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
        Radix22ButterflyG1_x_re_dly1 <= x_re;
        Radix22ButterflyG1_x_im_dly1 <= x_im_signed;
        Radix22ButterflyG1_x_vld_dly1 <= x_vld;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_1_enb AND dinXTwdl_1_1_vld_1;
      END IF;
    END IF;
  END PROCESS Radix22ButterflyG1_process;

  dinxTwdlf_vld <= ( NOT proc_1_enb) AND dinXTwdl_1_1_vld_1;
  dinXTwdlf_re <= dinXTwdl_re;
  dinXTwdlf_im <= dinXTwdl_im;
  btf1_re <= Radix22ButterflyG1_btf1_re_reg(17 DOWNTO 0);
  btf1_im <= Radix22ButterflyG1_btf1_im_reg(17 DOWNTO 0);
  btf2_re <= Radix22ButterflyG1_btf2_re_reg(17 DOWNTO 0);
  btf2_im <= Radix22ButterflyG1_btf2_im_reg(17 DOWNTO 0);

  dout_1_1_re <= dout_1_1_re_tmp;

  dout_1_1_im <= dout_1_1_im_tmp;

  dinXTwdl_1_1_vld <= dinXTwdl_1_1_vld_1;

END rtl;

