-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\idek11\RADIX22FFT_SDF1_3.vhd
-- Created: 2026-04-09 21:29:06
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RADIX22FFT_SDF1_3
-- Source Path: idek11/IFFT/RADIX22FFT_SDF1_3
-- Hierarchy Level: 2
-- Model version: 1.13
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.idek11_pkg.ALL;

ENTITY RADIX22FFT_SDF1_3 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        din_3_1_re_dly                    :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19
        din_3_1_im_dly                    :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19
        din_3_vld_dly                     :   IN    std_logic;
        rd_3_Addr                         :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        rd_3_Enb                          :   IN    std_logic;
        twdl_3_1_re                       :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
        twdl_3_1_im                       :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
        proc_3_enb                        :   IN    std_logic;
        dout_3_1_re                       :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20
        dout_3_1_im                       :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20
        dout_3_1_vld                      :   OUT   std_logic;
        dinXTwdl_3_1_vld                  :   OUT   std_logic
        );
END RADIX22FFT_SDF1_3;


ARCHITECTURE rtl OF RADIX22FFT_SDF1_3 IS

  -- Component Declarations
  COMPONENT Complex4Multiply
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          din_re                          :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20
          din_im                          :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20
          din_3_vld_dly                   :   IN    std_logic;
          twdl_3_1_re                     :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          twdl_3_1_im                     :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
          dinXTwdl_re                     :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20
          dinXTwdl_im                     :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20
          dinXTwdl_3_1_vld                :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          dout                            :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  COMPONENT SDFCommutator3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          din_3_vld_dly                   :   IN    std_logic;
          xf_re                           :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20
          xf_im                           :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20
          xf_vld                          :   IN    std_logic;
          dinXTwdlf_re                    :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20
          dinXTwdlf_im                    :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20
          dinxTwdlf_vld                   :   IN    std_logic;
          btf1_re                         :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20
          btf1_im                         :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20
          btf2_re                         :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20
          btf2_im                         :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20
          btf_vld                         :   IN    std_logic;
          wrData_re                       :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20
          wrData_im                       :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20
          wrAddr                          :   OUT   std_logic_vector(5 DOWNTO 0);  -- ufix6
          wrEnb                           :   OUT   std_logic;
          dout_3_1_re                     :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20
          dout_3_1_im                     :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20
          dout_3_1_vld                    :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Complex4Multiply
    USE ENTITY work.Complex4Multiply(rtl);

  FOR ALL : SimpleDualPortRAM_generic
    USE ENTITY work.SimpleDualPortRAM_generic(rtl);

  FOR ALL : SDFCommutator3
    USE ENTITY work.SDFCommutator3(rtl);

  -- Signals
  SIGNAL din_3_1_re_dly_signed            : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL din_re                           : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL din_3_1_im_dly_signed            : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL din_im                           : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL dinXTwdl_re                      : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL dinXTwdl_im                      : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL dinXTwdl_3_1_vld_1               : std_logic;
  SIGNAL dinXTwdl_re_signed               : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL dinXTwdl_im_signed               : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL x_vld                            : std_logic;
  SIGNAL btf2_im                          : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL btf2_re                          : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL btf1_im                          : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL btf1_re                          : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL dinXTwdlf_im                     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL dinXTwdlf_re                     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL xf_im                            : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL wrData_im                        : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL wrAddr                           : std_logic_vector(5 DOWNTO 0);  -- ufix6
  SIGNAL wrEnb                            : std_logic;
  SIGNAL x_im                             : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL x_im_signed                      : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL wrData_re                        : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL x_re                             : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL x_re_signed                      : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG1_btf1_re_reg   : signed(20 DOWNTO 0);  -- sfix21
  SIGNAL Radix22ButterflyG1_btf1_im_reg   : signed(20 DOWNTO 0);  -- sfix21
  SIGNAL Radix22ButterflyG1_btf2_re_reg   : signed(20 DOWNTO 0);  -- sfix21
  SIGNAL Radix22ButterflyG1_btf2_im_reg   : signed(20 DOWNTO 0);  -- sfix21
  SIGNAL Radix22ButterflyG1_x_re_dly1     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG1_x_im_dly1     : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG1_x_vld_dly1    : std_logic;
  SIGNAL Radix22ButterflyG1_dinXtwdl_re_dly1 : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG1_dinXtwdl_im_dly1 : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG1_dinXtwdl_re_dly2 : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG1_dinXtwdl_im_dly2 : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG1_dinXtwdl_vld_dly1 : std_logic;
  SIGNAL Radix22ButterflyG1_dinXtwdl_vld_dly2 : std_logic;
  SIGNAL xf_re                            : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL xf_vld                           : std_logic;
  SIGNAL dinxTwdlf_vld                    : std_logic;
  SIGNAL btf_vld                          : std_logic;
  SIGNAL dout_3_1_re_tmp                  : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL dout_3_1_im_tmp                  : std_logic_vector(19 DOWNTO 0);  -- ufix20

BEGIN
  u_MUL4 : Complex4Multiply
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => std_logic_vector(din_re),  -- sfix20
              din_im => std_logic_vector(din_im),  -- sfix20
              din_3_vld_dly => din_3_vld_dly,
              twdl_3_1_re => twdl_3_1_re,  -- sfix17_En15
              twdl_3_1_im => twdl_3_1_im,  -- sfix17_En15
              dinXTwdl_re => dinXTwdl_re,  -- sfix20
              dinXTwdl_im => dinXTwdl_im,  -- sfix20
              dinXTwdl_3_1_vld => dinXTwdl_3_1_vld_1
              );

  u_dataMEM_im_0_3 : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 6,
                 DataWidth => 20
                 )
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => wrData_im,
              wr_addr => wrAddr,
              wr_en => wrEnb,
              rd_addr => rd_3_Addr,
              dout => x_im
              );

  u_dataMEM_re_0_3 : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 6,
                 DataWidth => 20
                 )
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => wrData_re,
              wr_addr => wrAddr,
              wr_en => wrEnb,
              rd_addr => rd_3_Addr,
              dout => x_re
              );

  u_SDFCOMMUTATOR_3 : SDFCommutator3
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_3_vld_dly => din_3_vld_dly,
              xf_re => std_logic_vector(xf_re),  -- sfix20
              xf_im => std_logic_vector(xf_im),  -- sfix20
              xf_vld => xf_vld,
              dinXTwdlf_re => std_logic_vector(dinXTwdlf_re),  -- sfix20
              dinXTwdlf_im => std_logic_vector(dinXTwdlf_im),  -- sfix20
              dinxTwdlf_vld => dinxTwdlf_vld,
              btf1_re => std_logic_vector(btf1_re),  -- sfix20
              btf1_im => std_logic_vector(btf1_im),  -- sfix20
              btf2_re => std_logic_vector(btf2_re),  -- sfix20
              btf2_im => std_logic_vector(btf2_im),  -- sfix20
              btf_vld => btf_vld,
              wrData_re => wrData_re,  -- sfix20
              wrData_im => wrData_im,  -- sfix20
              wrAddr => wrAddr,  -- ufix6
              wrEnb => wrEnb,
              dout_3_1_re => dout_3_1_re_tmp,  -- sfix20
              dout_3_1_im => dout_3_1_im_tmp,  -- sfix20
              dout_3_1_vld => dout_3_1_vld
              );

  din_3_1_re_dly_signed <= signed(din_3_1_re_dly);

  din_re <= resize(din_3_1_re_dly_signed, 20);

  din_3_1_im_dly_signed <= signed(din_3_1_im_dly);

  din_im <= resize(din_3_1_im_dly_signed, 20);

  dinXTwdl_re_signed <= signed(dinXTwdl_re);

  dinXTwdl_im_signed <= signed(dinXTwdl_im);

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_vld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        x_vld <= rd_3_Enb;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  x_im_signed <= signed(x_im);

  x_re_signed <= signed(x_re);

  -- Radix22ButterflyG1
  Radix22ButterflyG1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Radix22ButterflyG1_btf1_re_reg <= to_signed(16#000000#, 21);
      Radix22ButterflyG1_btf1_im_reg <= to_signed(16#000000#, 21);
      Radix22ButterflyG1_btf2_re_reg <= to_signed(16#000000#, 21);
      Radix22ButterflyG1_btf2_im_reg <= to_signed(16#000000#, 21);
      Radix22ButterflyG1_x_re_dly1 <= to_signed(16#00000#, 20);
      Radix22ButterflyG1_x_im_dly1 <= to_signed(16#00000#, 20);
      Radix22ButterflyG1_x_vld_dly1 <= '0';
      xf_re <= to_signed(16#00000#, 20);
      xf_im <= to_signed(16#00000#, 20);
      xf_vld <= '0';
      Radix22ButterflyG1_dinXtwdl_re_dly1 <= to_signed(16#00000#, 20);
      Radix22ButterflyG1_dinXtwdl_im_dly1 <= to_signed(16#00000#, 20);
      Radix22ButterflyG1_dinXtwdl_re_dly2 <= to_signed(16#00000#, 20);
      Radix22ButterflyG1_dinXtwdl_im_dly2 <= to_signed(16#00000#, 20);
      Radix22ButterflyG1_dinXtwdl_vld_dly1 <= '0';
      Radix22ButterflyG1_dinXtwdl_vld_dly2 <= '0';
      btf_vld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xf_re <= Radix22ButterflyG1_x_re_dly1;
        xf_im <= Radix22ButterflyG1_x_im_dly1;
        xf_vld <= Radix22ButterflyG1_x_vld_dly1;
        btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
        Radix22ButterflyG1_btf1_re_reg <= resize(Radix22ButterflyG1_x_re_dly1, 21) + resize(Radix22ButterflyG1_dinXtwdl_re_dly2, 21);
        Radix22ButterflyG1_btf2_re_reg <= resize(Radix22ButterflyG1_x_re_dly1, 21) - resize(Radix22ButterflyG1_dinXtwdl_re_dly2, 21);
        Radix22ButterflyG1_btf1_im_reg <= resize(Radix22ButterflyG1_x_im_dly1, 21) + resize(Radix22ButterflyG1_dinXtwdl_im_dly2, 21);
        Radix22ButterflyG1_btf2_im_reg <= resize(Radix22ButterflyG1_x_im_dly1, 21) - resize(Radix22ButterflyG1_dinXtwdl_im_dly2, 21);
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re_signed;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im_signed;
        Radix22ButterflyG1_x_re_dly1 <= x_re_signed;
        Radix22ButterflyG1_x_im_dly1 <= x_im_signed;
        Radix22ButterflyG1_x_vld_dly1 <= x_vld;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_3_enb AND dinXTwdl_3_1_vld_1;
      END IF;
    END IF;
  END PROCESS Radix22ButterflyG1_process;

  dinxTwdlf_vld <= ( NOT proc_3_enb) AND dinXTwdl_3_1_vld_1;
  dinXTwdlf_re <= dinXTwdl_re_signed;
  dinXTwdlf_im <= dinXTwdl_im_signed;
  btf1_re <= Radix22ButterflyG1_btf1_re_reg(19 DOWNTO 0);
  btf1_im <= Radix22ButterflyG1_btf1_im_reg(19 DOWNTO 0);
  btf2_re <= Radix22ButterflyG1_btf2_re_reg(19 DOWNTO 0);
  btf2_im <= Radix22ButterflyG1_btf2_im_reg(19 DOWNTO 0);

  dout_3_1_re <= dout_3_1_re_tmp;

  dout_3_1_im <= dout_3_1_im_tmp;

  dinXTwdl_3_1_vld <= dinXTwdl_3_1_vld_1;

END rtl;

