-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\idek11\TWDLROM_9_1.vhd
-- Created: 2026-04-09 21:29:06
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: TWDLROM_9_1
-- Source Path: idek11/IFFT/TWDLROM_9_1
-- Hierarchy Level: 2
-- Model version: 1.13
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.idek11_pkg.ALL;

ENTITY TWDLROM_9_1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dout_8_1_vld                      :   IN    std_logic;
        twdl_9_re                         :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En15
        twdl_9_im                         :   OUT   std_logic_vector(16 DOWNTO 0)  -- sfix17_En15
        );
END TWDLROM_9_1;


ARCHITECTURE rtl OF TWDLROM_9_1 IS

  -- Constants
  CONSTANT Twiddle_re_table_data          : vector_of_signed17(0 TO 63) := 
    (to_signed(16#08000#, 17), to_signed(16#07FFE#, 17), to_signed(16#07FF6#, 17), to_signed(16#07FEA#, 17),
     to_signed(16#07FD9#, 17), to_signed(16#07FC2#, 17), to_signed(16#07FA7#, 17), to_signed(16#07F87#, 17),
     to_signed(16#07F62#, 17), to_signed(16#07F38#, 17), to_signed(16#07F0A#, 17), to_signed(16#07ED6#, 17),
     to_signed(16#07E9D#, 17), to_signed(16#07E60#, 17), to_signed(16#07E1E#, 17), to_signed(16#07DD6#, 17),
     to_signed(16#07D8A#, 17), to_signed(16#07D3A#, 17), to_signed(16#07CE4#, 17), to_signed(16#07C89#, 17),
     to_signed(16#07C2A#, 17), to_signed(16#07BC6#, 17), to_signed(16#07B5D#, 17), to_signed(16#07AEF#, 17),
     to_signed(16#07A7D#, 17), to_signed(16#07A06#, 17), to_signed(16#0798A#, 17), to_signed(16#0790A#, 17),
     to_signed(16#07885#, 17), to_signed(16#077FB#, 17), to_signed(16#0776C#, 17), to_signed(16#076D9#, 17),
     to_signed(16#07642#, 17), to_signed(16#075A6#, 17), to_signed(16#07505#, 17), to_signed(16#07460#, 17),
     to_signed(16#073B6#, 17), to_signed(16#07308#, 17), to_signed(16#07255#, 17), to_signed(16#0719E#, 17),
     to_signed(16#070E3#, 17), to_signed(16#07023#, 17), to_signed(16#06F5F#, 17), to_signed(16#06E97#, 17),
     to_signed(16#06DCA#, 17), to_signed(16#06CF9#, 17), to_signed(16#06C24#, 17), to_signed(16#06B4B#, 17),
     to_signed(16#06A6E#, 17), to_signed(16#0698C#, 17), to_signed(16#068A7#, 17), to_signed(16#067BD#, 17),
     to_signed(16#066D0#, 17), to_signed(16#065DE#, 17), to_signed(16#064E9#, 17), to_signed(16#063EF#, 17),
     to_signed(16#062F2#, 17), to_signed(16#061F1#, 17), to_signed(16#060EC#, 17), to_signed(16#05FE4#, 17),
     to_signed(16#05ED7#, 17), to_signed(16#05DC8#, 17), to_signed(16#05CB4#, 17), to_signed(16#05B9D#, 17));  -- sfix17 [64]
  CONSTANT Twiddle_im_table_data          : vector_of_signed17(0 TO 63) := 
    (to_signed(16#00000#, 17), to_signed(-16#00192#, 17), to_signed(-16#00324#, 17), to_signed(-16#004B6#, 17),
     to_signed(-16#00648#, 17), to_signed(-16#007D9#, 17), to_signed(-16#0096B#, 17), to_signed(-16#00AFB#, 17),
     to_signed(-16#00C8C#, 17), to_signed(-16#00E1C#, 17), to_signed(-16#00FAB#, 17), to_signed(-16#0113A#, 17),
     to_signed(-16#012C8#, 17), to_signed(-16#01455#, 17), to_signed(-16#015E2#, 17), to_signed(-16#0176E#, 17),
     to_signed(-16#018F9#, 17), to_signed(-16#01A83#, 17), to_signed(-16#01C0C#, 17), to_signed(-16#01D93#, 17),
     to_signed(-16#01F1A#, 17), to_signed(-16#0209F#, 17), to_signed(-16#02224#, 17), to_signed(-16#023A7#, 17),
     to_signed(-16#02528#, 17), to_signed(-16#026A8#, 17), to_signed(-16#02827#, 17), to_signed(-16#029A4#, 17),
     to_signed(-16#02B1F#, 17), to_signed(-16#02C99#, 17), to_signed(-16#02E11#, 17), to_signed(-16#02F87#, 17),
     to_signed(-16#030FC#, 17), to_signed(-16#0326E#, 17), to_signed(-16#033DF#, 17), to_signed(-16#0354E#, 17),
     to_signed(-16#036BA#, 17), to_signed(-16#03825#, 17), to_signed(-16#0398D#, 17), to_signed(-16#03AF3#, 17),
     to_signed(-16#03C57#, 17), to_signed(-16#03DB8#, 17), to_signed(-16#03F17#, 17), to_signed(-16#04074#, 17),
     to_signed(-16#041CE#, 17), to_signed(-16#04326#, 17), to_signed(-16#0447B#, 17), to_signed(-16#045CD#, 17),
     to_signed(-16#0471D#, 17), to_signed(-16#0486A#, 17), to_signed(-16#049B4#, 17), to_signed(-16#04AFB#, 17),
     to_signed(-16#04C40#, 17), to_signed(-16#04D81#, 17), to_signed(-16#04EC0#, 17), to_signed(-16#04FFB#, 17),
     to_signed(-16#05134#, 17), to_signed(-16#05269#, 17), to_signed(-16#0539B#, 17), to_signed(-16#054CA#, 17),
     to_signed(-16#055F6#, 17), to_signed(-16#0571E#, 17), to_signed(-16#05843#, 17), to_signed(-16#05964#, 17));  -- sfix17 [64]

  -- Signals
  SIGNAL Radix22TwdlMapping_cnt           : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Radix22TwdlMapping_phase         : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Radix22TwdlMapping_octantReg1    : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Radix22TwdlMapping_twdlAddr_raw  : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Radix22TwdlMapping_twdlAddrMap   : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Radix22TwdlMapping_twdl45Reg     : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg1      : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg2      : std_logic;
  SIGNAL Radix22TwdlMapping_cnt_next      : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Radix22TwdlMapping_phase_next    : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Radix22TwdlMapping_octantReg1_next : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Radix22TwdlMapping_twdlAddr_raw_next : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Radix22TwdlMapping_twdlAddrMap_next : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Radix22TwdlMapping_twdl45Reg_next : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg1_next : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg2_next : std_logic;
  SIGNAL twdlAddr                         : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL twdlAddrVld                      : std_logic;
  SIGNAL twdlOctant                       : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL twdl45                           : std_logic;
  SIGNAL twiddleS_re                      : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL twiddleReg_re                    : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17_En15
  SIGNAL twiddleS_im                      : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL twiddleReg_im                    : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17_En15
  SIGNAL twdlOctantReg                    : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL twdl45Reg                        : std_logic;
  SIGNAL twdl_9_re_tmp                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL twdl_9_im_tmp                    : signed(16 DOWNTO 0);  -- sfix17_En15

BEGIN
  -- Radix22TwdlMapping
  Radix22TwdlMapping_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Radix22TwdlMapping_octantReg1 <= to_unsigned(16#0#, 3);
      Radix22TwdlMapping_twdlAddr_raw <= to_unsigned(16#000#, 9);
      Radix22TwdlMapping_twdlAddrMap <= to_unsigned(16#00#, 6);
      Radix22TwdlMapping_twdl45Reg <= '0';
      Radix22TwdlMapping_dvldReg1 <= '0';
      Radix22TwdlMapping_dvldReg2 <= '0';
      Radix22TwdlMapping_cnt <= to_unsigned(16#00#, 7);
      Radix22TwdlMapping_phase <= to_unsigned(16#0#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Radix22TwdlMapping_cnt <= Radix22TwdlMapping_cnt_next;
        Radix22TwdlMapping_phase <= Radix22TwdlMapping_phase_next;
        Radix22TwdlMapping_octantReg1 <= Radix22TwdlMapping_octantReg1_next;
        Radix22TwdlMapping_twdlAddr_raw <= Radix22TwdlMapping_twdlAddr_raw_next;
        Radix22TwdlMapping_twdlAddrMap <= Radix22TwdlMapping_twdlAddrMap_next;
        Radix22TwdlMapping_twdl45Reg <= Radix22TwdlMapping_twdl45Reg_next;
        Radix22TwdlMapping_dvldReg1 <= Radix22TwdlMapping_dvldReg1_next;
        Radix22TwdlMapping_dvldReg2 <= Radix22TwdlMapping_dvldReg2_next;
      END IF;
    END IF;
  END PROCESS Radix22TwdlMapping_process;

  Radix22TwdlMapping_output : PROCESS (Radix22TwdlMapping_cnt, Radix22TwdlMapping_dvldReg1,
       Radix22TwdlMapping_dvldReg2, Radix22TwdlMapping_octantReg1,
       Radix22TwdlMapping_phase, Radix22TwdlMapping_twdl45Reg,
       Radix22TwdlMapping_twdlAddrMap, Radix22TwdlMapping_twdlAddr_raw,
       dout_8_1_vld)
    VARIABLE octant : unsigned(2 DOWNTO 0);
    VARIABLE cnt_cast : unsigned(8 DOWNTO 0);
    VARIABLE sub_cast : signed(19 DOWNTO 0);
    VARIABLE sub_temp : signed(19 DOWNTO 0);
    VARIABLE sub_cast_0 : signed(10 DOWNTO 0);
    VARIABLE sub_temp_0 : signed(10 DOWNTO 0);
    VARIABLE sub_cast_1 : signed(10 DOWNTO 0);
    VARIABLE sub_temp_1 : signed(10 DOWNTO 0);
    VARIABLE sub_cast_2 : signed(19 DOWNTO 0);
    VARIABLE sub_temp_2 : signed(19 DOWNTO 0);
    VARIABLE sub_cast_3 : signed(19 DOWNTO 0);
    VARIABLE sub_temp_3 : signed(19 DOWNTO 0);
  BEGIN
    sub_temp := to_signed(16#00000#, 20);
    sub_temp_0 := to_signed(16#000#, 11);
    sub_temp_1 := to_signed(16#000#, 11);
    sub_temp_2 := to_signed(16#00000#, 20);
    sub_temp_3 := to_signed(16#00000#, 20);
    sub_cast_3 := to_signed(16#00000#, 20);
    cnt_cast := to_unsigned(16#000#, 9);
    sub_cast_2 := to_signed(16#00000#, 20);
    sub_cast_1 := to_signed(16#000#, 11);
    sub_cast_0 := to_signed(16#000#, 11);
    sub_cast := to_signed(16#00000#, 20);
    Radix22TwdlMapping_cnt_next <= Radix22TwdlMapping_cnt;
    Radix22TwdlMapping_phase_next <= Radix22TwdlMapping_phase;
    Radix22TwdlMapping_dvldReg2_next <= Radix22TwdlMapping_dvldReg1;
    Radix22TwdlMapping_dvldReg1_next <= dout_8_1_vld;
    CASE Radix22TwdlMapping_twdlAddr_raw IS
      WHEN "001000000" =>
        octant := to_unsigned(16#0#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '1';
      WHEN "010000000" =>
        octant := to_unsigned(16#1#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '0';
      WHEN "011000000" =>
        octant := to_unsigned(16#2#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '1';
      WHEN "100000000" =>
        octant := to_unsigned(16#3#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '0';
      WHEN "101000000" =>
        octant := to_unsigned(16#4#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '1';
      WHEN OTHERS => 
        octant := Radix22TwdlMapping_twdlAddr_raw(8 DOWNTO 6);
        Radix22TwdlMapping_twdl45Reg_next <= '0';
    END CASE;
    Radix22TwdlMapping_octantReg1_next <= octant;
    CASE octant IS
      WHEN "000" =>
        Radix22TwdlMapping_twdlAddrMap_next <= Radix22TwdlMapping_twdlAddr_raw(5 DOWNTO 0);
      WHEN "001" =>
        sub_cast_0 := signed(resize(Radix22TwdlMapping_twdlAddr_raw, 11));
        sub_temp_0 := to_signed(16#080#, 11) - sub_cast_0;
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_0(5 DOWNTO 0));
      WHEN "010" =>
        sub_cast_1 := signed(resize(Radix22TwdlMapping_twdlAddr_raw, 11));
        sub_temp_1 := sub_cast_1 - to_signed(16#080#, 11);
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_1(5 DOWNTO 0));
      WHEN "011" =>
        sub_cast_2 := signed(resize(Radix22TwdlMapping_twdlAddr_raw & '0' & '0' & '0' & '0' & '0' & '0', 20));
        sub_temp_2 := to_signed(16#04000#, 20) - sub_cast_2;
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_2(11 DOWNTO 6));
      WHEN "100" =>
        sub_cast_3 := signed(resize(Radix22TwdlMapping_twdlAddr_raw & '0' & '0' & '0' & '0' & '0' & '0', 20));
        sub_temp_3 := sub_cast_3 - to_signed(16#04000#, 20);
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_3(11 DOWNTO 6));
      WHEN OTHERS => 
        sub_cast := signed(resize(Radix22TwdlMapping_twdlAddr_raw & '0' & '0' & '0' & '0' & '0' & '0', 20));
        sub_temp := to_signed(16#06000#, 20) - sub_cast;
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp(11 DOWNTO 6));
    END CASE;
    IF Radix22TwdlMapping_phase = to_unsigned(16#0#, 2) THEN 
      Radix22TwdlMapping_twdlAddr_raw_next <= to_unsigned(16#000#, 9);
    ELSIF Radix22TwdlMapping_phase = to_unsigned(16#1#, 2) THEN 
      Radix22TwdlMapping_twdlAddr_raw_next <= resize(Radix22TwdlMapping_cnt, 9) sll 1;
    ELSIF Radix22TwdlMapping_phase = to_unsigned(16#2#, 2) THEN 
      Radix22TwdlMapping_twdlAddr_raw_next <= resize(Radix22TwdlMapping_cnt, 9);
    ELSE 
      cnt_cast := resize(Radix22TwdlMapping_cnt, 9);
      Radix22TwdlMapping_twdlAddr_raw_next <= (cnt_cast sll 1) + cnt_cast;
    END IF;
    IF dout_8_1_vld = '1' AND (Radix22TwdlMapping_cnt > to_unsigned(16#3F#, 7)) THEN 
      Radix22TwdlMapping_phase_next <= Radix22TwdlMapping_phase + to_unsigned(16#1#, 2);
    END IF;
    IF dout_8_1_vld = '1' THEN 
      Radix22TwdlMapping_cnt_next <= Radix22TwdlMapping_cnt + to_unsigned(16#40#, 7);
    END IF;
    twdlAddr <= Radix22TwdlMapping_twdlAddrMap;
    twdlAddrVld <= Radix22TwdlMapping_dvldReg2;
    twdlOctant <= Radix22TwdlMapping_octantReg1;
    twdl45 <= Radix22TwdlMapping_twdl45Reg;
  END PROCESS Radix22TwdlMapping_output;


  -- Twiddle ROM1
  twiddleS_re <= Twiddle_re_table_data(to_integer(twdlAddr));

  TWIDDLEROM_RE_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        twiddleReg_re <= twiddleS_re;
      END IF;
    END IF;
  END PROCESS TWIDDLEROM_RE_process;


  -- Twiddle ROM2
  twiddleS_im <= Twiddle_im_table_data(to_integer(twdlAddr));

  TWIDDLEROM_IM_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        twiddleReg_im <= twiddleS_im;
      END IF;
    END IF;
  END PROCESS TWIDDLEROM_IM_process;


  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twdlOctantReg <= to_unsigned(16#0#, 3);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        twdlOctantReg <= twdlOctant;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twdl45Reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        twdl45Reg <= twdl45;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  -- Radix22TwdlOctCorr
  Radix22TwdlOctCorr_output : PROCESS (twdl45Reg, twdlOctantReg, twiddleReg_im, twiddleReg_re)
    VARIABLE twdlIn_re : signed(16 DOWNTO 0);
    VARIABLE twdlIn_im : signed(16 DOWNTO 0);
    VARIABLE cast : signed(17 DOWNTO 0);
    VARIABLE cast_0 : signed(17 DOWNTO 0);
    VARIABLE cast_1 : signed(17 DOWNTO 0);
    VARIABLE cast_2 : signed(17 DOWNTO 0);
    VARIABLE cast_3 : signed(17 DOWNTO 0);
    VARIABLE cast_4 : signed(17 DOWNTO 0);
    VARIABLE cast_5 : signed(17 DOWNTO 0);
    VARIABLE cast_6 : signed(17 DOWNTO 0);
    VARIABLE cast_7 : signed(17 DOWNTO 0);
    VARIABLE cast_8 : signed(17 DOWNTO 0);
    VARIABLE cast_9 : signed(17 DOWNTO 0);
    VARIABLE cast_10 : signed(17 DOWNTO 0);
  BEGIN
    cast_0 := to_signed(16#00000#, 18);
    cast_2 := to_signed(16#00000#, 18);
    cast_4 := to_signed(16#00000#, 18);
    cast_6 := to_signed(16#00000#, 18);
    cast_8 := to_signed(16#00000#, 18);
    cast_10 := to_signed(16#00000#, 18);
    cast_3 := to_signed(16#00000#, 18);
    cast_9 := to_signed(16#00000#, 18);
    cast_1 := to_signed(16#00000#, 18);
    cast_7 := to_signed(16#00000#, 18);
    cast := to_signed(16#00000#, 18);
    cast_5 := to_signed(16#00000#, 18);
    twdlIn_re := twiddleReg_re;
    twdlIn_im := twiddleReg_im;
    IF twdl45Reg = '1' THEN 
      CASE twdlOctantReg IS
        WHEN "000" =>
          twdlIn_re := to_signed(16#05A82#, 17);
          twdlIn_im := to_signed(-16#05A82#, 17);
        WHEN "010" =>
          twdlIn_re := to_signed(-16#05A82#, 17);
          twdlIn_im := to_signed(-16#05A82#, 17);
        WHEN "100" =>
          twdlIn_re := to_signed(-16#05A82#, 17);
          twdlIn_im := to_signed(16#05A82#, 17);
        WHEN OTHERS => 
          twdlIn_re := to_signed(16#05A82#, 17);
          twdlIn_im := to_signed(-16#05A82#, 17);
      END CASE;
    ELSE 
      CASE twdlOctantReg IS
        WHEN "000" =>
          NULL;
        WHEN "001" =>
          cast := resize(twiddleReg_im, 18);
          cast_0 :=  - (cast);
          twdlIn_re := cast_0(16 DOWNTO 0);
          cast_5 := resize(twiddleReg_re, 18);
          cast_6 :=  - (cast_5);
          twdlIn_im := cast_6(16 DOWNTO 0);
        WHEN "010" =>
          twdlIn_re := twiddleReg_im;
          cast_7 := resize(twiddleReg_re, 18);
          cast_8 :=  - (cast_7);
          twdlIn_im := cast_8(16 DOWNTO 0);
        WHEN "011" =>
          cast_1 := resize(twiddleReg_re, 18);
          cast_2 :=  - (cast_1);
          twdlIn_re := cast_2(16 DOWNTO 0);
          twdlIn_im := twiddleReg_im;
        WHEN "100" =>
          cast_3 := resize(twiddleReg_re, 18);
          cast_4 :=  - (cast_3);
          twdlIn_re := cast_4(16 DOWNTO 0);
          cast_9 := resize(twiddleReg_im, 18);
          cast_10 :=  - (cast_9);
          twdlIn_im := cast_10(16 DOWNTO 0);
        WHEN OTHERS => 
          twdlIn_re := twiddleReg_im;
          twdlIn_im := twiddleReg_re;
      END CASE;
    END IF;
    twdl_9_re_tmp <= twdlIn_re;
    twdl_9_im_tmp <= twdlIn_im;
  END PROCESS Radix22TwdlOctCorr_output;


  twdl_9_re <= std_logic_vector(twdl_9_re_tmp);

  twdl_9_im <= std_logic_vector(twdl_9_im_tmp);

END rtl;

