SLStudio.Utils.RemoveHighlighting(get_param('SignalGenerator', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_SignalGenerator', 'handle'));
annotate_port('gm_SignalGenerator/Direct Lookup Table (n-D)', 0, 1, '');
annotate_port('SignalGenerator/Direct Lookup Table (n-D)', 0, 1, '');
annotate_port('gm_SignalGenerator/Direct Lookup Table (n-D)', 0, 1, '');
annotate_port('SignalGenerator/Direct Lookup Table (n-D)', 0, 1, '');
annotate_port('gm_SignalGenerator/Direct Lookup Table (n-D)1', 0, 1, '');
annotate_port('SignalGenerator/Direct Lookup Table (n-D)1', 0, 1, '');
annotate_port('gm_SignalGenerator/Direct Lookup Table (n-D)1', 0, 1, '');
annotate_port('SignalGenerator/Direct Lookup Table (n-D)1', 0, 1, '');
annotate_port('gm_SignalGenerator/IFFT', 0, 1, '');
annotate_port('SignalGenerator/IFFT', 0, 1, '');
annotate_port('gm_SignalGenerator/IFFT', 0, 1, '');
annotate_port('SignalGenerator/IFFT', 0, 1, '');
annotate_port('gm_SignalGenerator/IFFT', 0, 1, '');
annotate_port('SignalGenerator/IFFT', 0, 1, '');
annotate_port('gm_SignalGenerator/IFFT', 0, 1, '');
annotate_port('SignalGenerator/IFFT', 0, 1, '');
