-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\SignalGenerator\Complex3Multiply_block2.vhd
-- Created: 2026-05-02 22:03:18
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Complex3Multiply_block2
-- Source Path: SignalGenerator/IFFT/RADIX22FFT_SDF1_9/Complex3Multiply
-- Hierarchy Level: 3
-- Model version: 2.7
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Complex3Multiply_block2 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        din_re                            :   IN    std_logic_vector(40 DOWNTO 0);  -- sfix41_En17
        din_im                            :   IN    std_logic_vector(40 DOWNTO 0);  -- sfix41_En17
        din_9_vld_dly                     :   IN    std_logic;
        twdl_9_re                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        twdl_9_im                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        dinXTwdl_re                       :   OUT   std_logic_vector(40 DOWNTO 0);  -- sfix41_En17
        dinXTwdl_im                       :   OUT   std_logic_vector(40 DOWNTO 0);  -- sfix41_En17
        dinXTwdl_9_vld                    :   OUT   std_logic
        );
END Complex3Multiply_block2;


ARCHITECTURE rtl OF Complex3Multiply_block2 IS

  -- Signals
  SIGNAL din_re_signed                    : signed(40 DOWNTO 0);  -- sfix41_En17
  SIGNAL din_re_reg                       : signed(40 DOWNTO 0);  -- sfix41_En17
  SIGNAL din_im_signed                    : signed(40 DOWNTO 0);  -- sfix41_En17
  SIGNAL din_im_reg                       : signed(40 DOWNTO 0);  -- sfix41_En17
  SIGNAL adder_add_cast                   : signed(41 DOWNTO 0);  -- sfix42_En17
  SIGNAL adder_add_cast_1                 : signed(41 DOWNTO 0);  -- sfix42_En17
  SIGNAL din_sum                          : signed(41 DOWNTO 0);  -- sfix42_En17
  SIGNAL twdl_9_re_signed                 : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL twdl_re_reg                      : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL twdl_9_im_signed                 : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL twdl_im_reg                      : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL adder_add_cast_2                 : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL adder_add_cast_3                 : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL twdl_sum                         : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL Complex3Multiply_din1_re_pipe1   : signed(40 DOWNTO 0) := to_signed(0, 41);  -- sfix41
  SIGNAL Complex3Multiply_din1_im_pipe1   : signed(40 DOWNTO 0) := to_signed(0, 41);  -- sfix41
  SIGNAL Complex3Multiply_din1_sum_pipe1  : signed(41 DOWNTO 0) := to_signed(0, 42);  -- sfix42
  SIGNAL Complex3Multiply_prodOfRe_pipe1  : signed(72 DOWNTO 0) := to_signed(0, 73);  -- sfix73
  SIGNAL Complex3Multiply_ProdOfIm_pipe1  : signed(72 DOWNTO 0) := to_signed(0, 73);  -- sfix73
  SIGNAL Complex3Multiply_prodOfSum_pipe1 : signed(74 DOWNTO 0) := to_signed(0, 75);  -- sfix75
  SIGNAL Complex3Multiply_twiddle_re_pipe1 : signed(31 DOWNTO 0) := to_signed(0, 32);  -- sfix32
  SIGNAL Complex3Multiply_twiddle_im_pipe1 : signed(31 DOWNTO 0) := to_signed(0, 32);  -- sfix32
  SIGNAL Complex3Multiply_twiddle_sum_pipe1 : signed(32 DOWNTO 0) := to_signed(0, 33);  -- sfix33
  SIGNAL prodOfRe                         : signed(72 DOWNTO 0) := to_signed(0, 73);  -- sfix73_En47
  SIGNAL prodOfIm                         : signed(72 DOWNTO 0) := to_signed(0, 73);  -- sfix73_En47
  SIGNAL prodOfSum                        : signed(74 DOWNTO 0) := to_signed(0, 75);  -- sfix75_En47
  SIGNAL din_vld_dly1                     : std_logic;
  SIGNAL din_vld_dly2                     : std_logic;
  SIGNAL din_vld_dly3                     : std_logic;
  SIGNAL prod_vld                         : std_logic;
  SIGNAL Complex3Add_tmpResult_reg        : signed(74 DOWNTO 0);  -- sfix75
  SIGNAL Complex3Add_multRes_re_reg1      : signed(73 DOWNTO 0);  -- sfix74
  SIGNAL Complex3Add_multRes_re_reg2      : signed(73 DOWNTO 0);  -- sfix74
  SIGNAL Complex3Add_multRes_im_reg       : signed(75 DOWNTO 0);  -- sfix76
  SIGNAL Complex3Add_prod_vld_reg1        : std_logic;
  SIGNAL Complex3Add_prodOfSum_reg        : signed(74 DOWNTO 0);  -- sfix75
  SIGNAL Complex3Add_tmpResult_reg_next   : signed(74 DOWNTO 0);  -- sfix75_En47
  SIGNAL Complex3Add_multRes_re_reg1_next : signed(73 DOWNTO 0);  -- sfix74_En47
  SIGNAL Complex3Add_multRes_re_reg2_next : signed(73 DOWNTO 0);  -- sfix74_En47
  SIGNAL Complex3Add_multRes_im_reg_next  : signed(75 DOWNTO 0);  -- sfix76_En47
  SIGNAL Complex3Add_sub_cast             : signed(73 DOWNTO 0);  -- sfix74_En47
  SIGNAL Complex3Add_sub_cast_1           : signed(73 DOWNTO 0);  -- sfix74_En47
  SIGNAL Complex3Add_sub_cast_2           : signed(75 DOWNTO 0);  -- sfix76_En47
  SIGNAL Complex3Add_sub_cast_3           : signed(75 DOWNTO 0);  -- sfix76_En47
  SIGNAL Complex3Add_add_cast             : signed(73 DOWNTO 0);  -- sfix74_En47
  SIGNAL Complex3Add_add_cast_1           : signed(73 DOWNTO 0);  -- sfix74_En47
  SIGNAL Complex3Add_add_temp             : signed(73 DOWNTO 0);  -- sfix74_En47
  SIGNAL multResFP_re                     : signed(73 DOWNTO 0);  -- sfix74_En47
  SIGNAL multResFP_im                     : signed(75 DOWNTO 0);  -- sfix76_En47
  SIGNAL dinXTwdl_9_vld_1                 : std_logic;
  SIGNAL dinXTwdl_re_tmp                  : signed(40 DOWNTO 0);  -- sfix41_En17
  SIGNAL dinXTwdl_im_tmp                  : signed(40 DOWNTO 0);  -- sfix41_En17

BEGIN
  din_re_signed <= signed(din_re);

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      din_re_reg <= to_signed(0, 41);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        din_re_reg <= din_re_signed;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  din_im_signed <= signed(din_im);

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      din_im_reg <= to_signed(0, 41);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        din_im_reg <= din_im_signed;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  adder_add_cast <= resize(din_re_reg, 42);
  adder_add_cast_1 <= resize(din_im_reg, 42);
  din_sum <= adder_add_cast + adder_add_cast_1;

  twdl_9_re_signed <= signed(twdl_9_re);

  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      twdl_re_reg <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        twdl_re_reg <= twdl_9_re_signed;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  twdl_9_im_signed <= signed(twdl_9_im);

  intdelay_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      twdl_im_reg <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        twdl_im_reg <= twdl_9_im_signed;
      END IF;
    END IF;
  END PROCESS intdelay_3_process;


  adder_add_cast_2 <= resize(twdl_re_reg, 33);
  adder_add_cast_3 <= resize(twdl_im_reg, 33);
  twdl_sum <= adder_add_cast_2 + adder_add_cast_3;

  -- Complex3Multiply
  Complex3Multiply_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        prodOfRe <= Complex3Multiply_prodOfRe_pipe1;
        prodOfIm <= Complex3Multiply_ProdOfIm_pipe1;
        prodOfSum <= Complex3Multiply_prodOfSum_pipe1;
        Complex3Multiply_prodOfRe_pipe1 <= Complex3Multiply_din1_re_pipe1 * Complex3Multiply_twiddle_re_pipe1;
        Complex3Multiply_ProdOfIm_pipe1 <= Complex3Multiply_din1_im_pipe1 * Complex3Multiply_twiddle_im_pipe1;
        Complex3Multiply_prodOfSum_pipe1 <= Complex3Multiply_din1_sum_pipe1 * Complex3Multiply_twiddle_sum_pipe1;
        Complex3Multiply_twiddle_re_pipe1 <= twdl_re_reg;
        Complex3Multiply_twiddle_im_pipe1 <= twdl_im_reg;
        Complex3Multiply_twiddle_sum_pipe1 <= twdl_sum;
        Complex3Multiply_din1_re_pipe1 <= din_re_reg;
        Complex3Multiply_din1_im_pipe1 <= din_im_reg;
        Complex3Multiply_din1_sum_pipe1 <= din_sum;
      END IF;
    END IF;
  END PROCESS Complex3Multiply_process;


  intdelay_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      din_vld_dly1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        din_vld_dly1 <= din_9_vld_dly;
      END IF;
    END IF;
  END PROCESS intdelay_4_process;


  intdelay_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      din_vld_dly2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        din_vld_dly2 <= din_vld_dly1;
      END IF;
    END IF;
  END PROCESS intdelay_5_process;


  intdelay_6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      din_vld_dly3 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        din_vld_dly3 <= din_vld_dly2;
      END IF;
    END IF;
  END PROCESS intdelay_6_process;


  intdelay_7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      prod_vld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        prod_vld <= din_vld_dly3;
      END IF;
    END IF;
  END PROCESS intdelay_7_process;


  -- Complex3Add
  Complex3Add_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Complex3Add_prodOfSum_reg <= to_signed(0, 75);
      Complex3Add_tmpResult_reg <= to_signed(0, 75);
      Complex3Add_multRes_re_reg1 <= to_signed(0, 74);
      Complex3Add_multRes_re_reg2 <= to_signed(0, 74);
      Complex3Add_multRes_im_reg <= to_signed(0, 76);
      Complex3Add_prod_vld_reg1 <= '0';
      dinXTwdl_9_vld_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Complex3Add_tmpResult_reg <= Complex3Add_tmpResult_reg_next;
        Complex3Add_multRes_re_reg1 <= Complex3Add_multRes_re_reg1_next;
        Complex3Add_multRes_re_reg2 <= Complex3Add_multRes_re_reg2_next;
        Complex3Add_multRes_im_reg <= Complex3Add_multRes_im_reg_next;
        Complex3Add_prodOfSum_reg <= prodOfSum;
        dinXTwdl_9_vld_1 <= Complex3Add_prod_vld_reg1;
        Complex3Add_prod_vld_reg1 <= prod_vld;
      END IF;
    END IF;
  END PROCESS Complex3Add_process;

  Complex3Add_multRes_re_reg2_next <= Complex3Add_multRes_re_reg1;
  Complex3Add_sub_cast <= resize(prodOfRe, 74);
  Complex3Add_sub_cast_1 <= resize(prodOfIm, 74);
  Complex3Add_multRes_re_reg1_next <= Complex3Add_sub_cast - Complex3Add_sub_cast_1;
  Complex3Add_sub_cast_2 <= resize(Complex3Add_prodOfSum_reg, 76);
  Complex3Add_sub_cast_3 <= resize(Complex3Add_tmpResult_reg, 76);
  Complex3Add_multRes_im_reg_next <= Complex3Add_sub_cast_2 - Complex3Add_sub_cast_3;
  Complex3Add_add_cast <= resize(prodOfRe, 74);
  Complex3Add_add_cast_1 <= resize(prodOfIm, 74);
  Complex3Add_add_temp <= Complex3Add_add_cast + Complex3Add_add_cast_1;
  Complex3Add_tmpResult_reg_next <= resize(Complex3Add_add_temp, 75);
  multResFP_re <= Complex3Add_multRes_re_reg2;
  multResFP_im <= Complex3Add_multRes_im_reg;

  dinXTwdl_re_tmp <= multResFP_re(70 DOWNTO 30) + ('0' & multResFP_re(29));

  dinXTwdl_re <= std_logic_vector(dinXTwdl_re_tmp);

  dinXTwdl_im_tmp <= multResFP_im(70 DOWNTO 30) + ('0' & multResFP_im(29));

  dinXTwdl_im <= std_logic_vector(dinXTwdl_im_tmp);

  dinXTwdl_9_vld <= dinXTwdl_9_vld_1;

END rtl;

