open_system('SignalGenerator');
open_system('gm_SignalGenerator');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SignalGenerator/Direct Lookup Table (n-D)', 'user1');
annotate_port('gm_SignalGenerator/Direct Lookup Table (n-D)', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('SignalGenerator/Direct Lookup Table (n-D)', 'user1');
annotate_port('SignalGenerator/Direct Lookup Table (n-D)', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SignalGenerator/Direct Lookup Table (n-D)1', 'user1');
annotate_port('gm_SignalGenerator/Direct Lookup Table (n-D)1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('SignalGenerator/Direct Lookup Table (n-D)1', 'user1');
annotate_port('SignalGenerator/Direct Lookup Table (n-D)1', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SignalGenerator/IFFT', 'user1');
annotate_port('gm_SignalGenerator/IFFT', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('SignalGenerator/IFFT', 'user1');
annotate_port('SignalGenerator/IFFT', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SignalGenerator/IFFT', 'user1');
annotate_port('gm_SignalGenerator/IFFT', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('SignalGenerator/IFFT', 'user1');
annotate_port('SignalGenerator/IFFT', 0, 1, 'Delays not moved across an unsupported block');
