open_system('SignalGenerator');
open_system('gm_SignalGenerator');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SignalGenerator/IFFT', 'user1');
annotate_port('gm_SignalGenerator/IFFT', 0, 1, 'Blocks delay absorption: 1 cycles');
hilite_system('SignalGenerator/IFFT', 'user1');
annotate_port('SignalGenerator/IFFT', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SignalGenerator/IFFT', 'user1');
annotate_port('gm_SignalGenerator/IFFT', 0, 1, 'Blocks delay absorption: 1 cycles');
hilite_system('SignalGenerator/IFFT', 'user1');
annotate_port('SignalGenerator/IFFT', 0, 1, 'Blocks delay absorption: 1 cycles');
