open_system('SignalGenerator');
open_system('gm_SignalGenerator');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SignalGenerator/Direct Lookup Table (n-D)', 'user1');
annotate_port('gm_SignalGenerator/Direct Lookup Table (n-D)', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('SignalGenerator/Direct Lookup Table (n-D)', 'user1');
annotate_port('SignalGenerator/Direct Lookup Table (n-D)', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SignalGenerator/Direct Lookup Table (n-D)1', 'user1');
annotate_port('gm_SignalGenerator/Direct Lookup Table (n-D)1', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('SignalGenerator/Direct Lookup Table (n-D)1', 'user1');
annotate_port('SignalGenerator/Direct Lookup Table (n-D)1', 0, 1, 'Lookup Table mapped to RAM');
