-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\SignalGenerator\SignalGenerator.vhd
-- Created: 2026-05-02 12:01:45
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 3.25521e-09
-- Target subsystem base rate: 3.25521e-09
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        3.25521e-09
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1_re                       ce_out        3.25521e-09
-- Out1_im                       ce_out        3.25521e-09
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SignalGenerator
-- Source Path: SignalGenerator
-- Hierarchy Level: 0
-- Model version: 2.2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SignalGenerator_pkg.ALL;

ENTITY SignalGenerator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out1_re                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        Out1_im                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END SignalGenerator;


ARCHITECTURE rtl OF SignalGenerator IS

  -- Component Declarations
  COMPONENT IFFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          dataIn_im                       :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(40 DOWNTO 0);  -- sfix41
          dataOut_im                      :   OUT   std_logic_vector(40 DOWNTO 0)  -- sfix41
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : IFFT
    USE ENTITY work.IFFT(rtl);

  -- Constants
  CONSTANT Direct_Lookup_Table_n_D_table_data : vector_of_signed32(0 TO 511) := 
    (to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(1210, 32), to_signed(1209, 32),
     to_signed(1200, 32), to_signed(1162, 32), to_signed(1060, 32), to_signed(856, 32), to_signed(515, 32),
     to_signed(38, 32), to_signed(-515, 32), to_signed(-1001, 32), to_signed(-1210, 32), to_signed(-956, 32),
     to_signed(-227, 32), to_signed(680, 32), to_signed(1200, 32), to_signed(856, 32), to_signed(-227, 32),
     to_signed(-1138, 32), to_signed(-882, 32), to_signed(410, 32), to_signed(1210, 32), to_signed(338, 32),
     to_signed(-1060, 32), to_signed(-742, 32), to_signed(882, 32), to_signed(856, 32), to_signed(-882, 32),
     to_signed(-742, 32), to_signed(1060, 32), to_signed(338, 32), to_signed(-1210, 32), to_signed(410, 32),
     to_signed(882, 32), to_signed(-1138, 32), to_signed(227, 32), to_signed(856, 32), to_signed(-1200, 32),
     to_signed(680, 32), to_signed(227, 32), to_signed(-956, 32), to_signed(1210, 32), to_signed(-1001, 32),
     to_signed(515, 32), to_signed(38, 32), to_signed(-515, 32), to_signed(856, 32), to_signed(-1060, 32),
     to_signed(1162, 32), to_signed(-1200, 32), to_signed(1209, 32), to_signed(-1210, 32), to_signed(1209, 32),
     to_signed(-1200, 32), to_signed(1162, 32), to_signed(-1060, 32), to_signed(856, 32), to_signed(-515, 32),
     to_signed(38, 32), to_signed(515, 32), to_signed(-1001, 32), to_signed(1210, 32), to_signed(-956, 32),
     to_signed(227, 32), to_signed(680, 32), to_signed(-1200, 32), to_signed(856, 32), to_signed(227, 32),
     to_signed(-1138, 32), to_signed(882, 32), to_signed(410, 32), to_signed(-1210, 32), to_signed(338, 32),
     to_signed(1060, 32), to_signed(-742, 32), to_signed(-882, 32), to_signed(856, 32), to_signed(882, 32),
     to_signed(-742, 32), to_signed(-1060, 32), to_signed(338, 32), to_signed(1210, 32), to_signed(410, 32),
     to_signed(-882, 32), to_signed(-1138, 32), to_signed(-227, 32), to_signed(856, 32), to_signed(1200, 32),
     to_signed(680, 32), to_signed(-227, 32), to_signed(-956, 32), to_signed(-1210, 32), to_signed(-1001, 32),
     to_signed(-515, 32), to_signed(38, 32), to_signed(515, 32), to_signed(856, 32), to_signed(1060, 32),
     to_signed(1162, 32), to_signed(1200, 32), to_signed(1209, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(1209, 32), to_signed(1200, 32), to_signed(1162, 32), to_signed(1060, 32), to_signed(856, 32),
     to_signed(515, 32), to_signed(38, 32), to_signed(-515, 32), to_signed(-1001, 32), to_signed(-1210, 32),
     to_signed(-956, 32), to_signed(-227, 32), to_signed(680, 32), to_signed(1200, 32), to_signed(856, 32),
     to_signed(-227, 32), to_signed(-1138, 32), to_signed(-882, 32), to_signed(410, 32), to_signed(1210, 32),
     to_signed(338, 32), to_signed(-1060, 32), to_signed(-742, 32), to_signed(882, 32), to_signed(856, 32),
     to_signed(-882, 32), to_signed(-742, 32), to_signed(1060, 32), to_signed(338, 32), to_signed(-1210, 32),
     to_signed(410, 32), to_signed(882, 32), to_signed(-1138, 32), to_signed(227, 32), to_signed(856, 32),
     to_signed(-1200, 32), to_signed(680, 32), to_signed(227, 32), to_signed(-956, 32), to_signed(1210, 32),
     to_signed(-1001, 32), to_signed(515, 32), to_signed(38, 32), to_signed(-515, 32), to_signed(856, 32),
     to_signed(-1060, 32), to_signed(1162, 32), to_signed(-1200, 32), to_signed(1209, 32), to_signed(-1210, 32),
     to_signed(1209, 32), to_signed(-1200, 32), to_signed(1162, 32), to_signed(-1060, 32), to_signed(856, 32),
     to_signed(-515, 32), to_signed(38, 32), to_signed(515, 32), to_signed(-1001, 32), to_signed(1210, 32),
     to_signed(-956, 32), to_signed(227, 32), to_signed(680, 32), to_signed(-1200, 32), to_signed(856, 32),
     to_signed(227, 32), to_signed(-1138, 32), to_signed(882, 32), to_signed(410, 32), to_signed(-1210, 32),
     to_signed(338, 32), to_signed(1060, 32), to_signed(-742, 32), to_signed(-882, 32), to_signed(856, 32),
     to_signed(882, 32), to_signed(-742, 32), to_signed(-1060, 32), to_signed(338, 32), to_signed(1210, 32),
     to_signed(410, 32), to_signed(-882, 32), to_signed(-1138, 32), to_signed(-227, 32), to_signed(856, 32),
     to_signed(1200, 32), to_signed(680, 32), to_signed(-227, 32), to_signed(-956, 32), to_signed(-1210, 32),
     to_signed(-1001, 32), to_signed(-515, 32), to_signed(38, 32), to_signed(515, 32), to_signed(856, 32),
     to_signed(1060, 32), to_signed(1162, 32), to_signed(1200, 32), to_signed(1209, 32), to_signed(1210, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32));  -- sfix32 [512]
  CONSTANT Direct_Lookup_Table_n_D_1_table_data : vector_of_signed32(0 TO 511) := 
    (to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(38, 32),
     to_signed(152, 32), to_signed(338, 32), to_signed(583, 32), to_signed(856, 32), to_signed(1095, 32),
     to_signed(1209, 32), to_signed(1095, 32), to_signed(680, 32), to_signed(0, 32), to_signed(-742, 32),
     to_signed(-1189, 32), to_signed(-1001, 32), to_signed(-152, 32), to_signed(856, 32), to_signed(1189, 32),
     to_signed(410, 32), to_signed(-828, 32), to_signed(-1138, 32), to_signed(0, 32), to_signed(1162, 32),
     to_signed(583, 32), to_signed(-956, 32), to_signed(-828, 32), to_signed(856, 32), to_signed(828, 32),
     to_signed(-956, 32), to_signed(-583, 32), to_signed(1162, 32), to_signed(0, 32), to_signed(-1138, 32),
     to_signed(828, 32), to_signed(410, 32), to_signed(-1189, 32), to_signed(856, 32), to_signed(152, 32),
     to_signed(-1001, 32), to_signed(1189, 32), to_signed(-742, 32), to_signed(0, 32), to_signed(680, 32),
     to_signed(-1095, 32), to_signed(1209, 32), to_signed(-1095, 32), to_signed(856, 32), to_signed(-583, 32),
     to_signed(338, 32), to_signed(-152, 32), to_signed(38, 32), to_signed(0, 32), to_signed(38, 32),
     to_signed(-152, 32), to_signed(338, 32), to_signed(-583, 32), to_signed(856, 32), to_signed(-1095, 32),
     to_signed(1209, 32), to_signed(-1095, 32), to_signed(680, 32), to_signed(0, 32), to_signed(-742, 32),
     to_signed(1189, 32), to_signed(-1001, 32), to_signed(152, 32), to_signed(856, 32), to_signed(-1189, 32),
     to_signed(410, 32), to_signed(828, 32), to_signed(-1138, 32), to_signed(0, 32), to_signed(1162, 32),
     to_signed(-583, 32), to_signed(-956, 32), to_signed(828, 32), to_signed(856, 32), to_signed(-828, 32),
     to_signed(-956, 32), to_signed(583, 32), to_signed(1162, 32), to_signed(0, 32), to_signed(-1138, 32),
     to_signed(-828, 32), to_signed(410, 32), to_signed(1189, 32), to_signed(856, 32), to_signed(-152, 32),
     to_signed(-1001, 32), to_signed(-1189, 32), to_signed(-742, 32), to_signed(0, 32), to_signed(680, 32),
     to_signed(1095, 32), to_signed(1209, 32), to_signed(1095, 32), to_signed(856, 32), to_signed(583, 32),
     to_signed(338, 32), to_signed(152, 32), to_signed(38, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(-38, 32),
     to_signed(-152, 32), to_signed(-338, 32), to_signed(-583, 32), to_signed(-856, 32), to_signed(-1095, 32),
     to_signed(-1209, 32), to_signed(-1095, 32), to_signed(-680, 32), to_signed(0, 32), to_signed(742, 32),
     to_signed(1189, 32), to_signed(1001, 32), to_signed(152, 32), to_signed(-856, 32), to_signed(-1189, 32),
     to_signed(-410, 32), to_signed(828, 32), to_signed(1138, 32), to_signed(0, 32), to_signed(-1162, 32),
     to_signed(-583, 32), to_signed(956, 32), to_signed(828, 32), to_signed(-856, 32), to_signed(-828, 32),
     to_signed(956, 32), to_signed(583, 32), to_signed(-1162, 32), to_signed(0, 32), to_signed(1138, 32),
     to_signed(-828, 32), to_signed(-410, 32), to_signed(1189, 32), to_signed(-856, 32), to_signed(-152, 32),
     to_signed(1001, 32), to_signed(-1189, 32), to_signed(742, 32), to_signed(0, 32), to_signed(-680, 32),
     to_signed(1095, 32), to_signed(-1209, 32), to_signed(1095, 32), to_signed(-856, 32), to_signed(583, 32),
     to_signed(-338, 32), to_signed(152, 32), to_signed(-38, 32), to_signed(0, 32), to_signed(-38, 32),
     to_signed(152, 32), to_signed(-338, 32), to_signed(583, 32), to_signed(-856, 32), to_signed(1095, 32),
     to_signed(-1209, 32), to_signed(1095, 32), to_signed(-680, 32), to_signed(0, 32), to_signed(742, 32),
     to_signed(-1189, 32), to_signed(1001, 32), to_signed(-152, 32), to_signed(-856, 32), to_signed(1189, 32),
     to_signed(-410, 32), to_signed(-828, 32), to_signed(1138, 32), to_signed(0, 32), to_signed(-1162, 32),
     to_signed(583, 32), to_signed(956, 32), to_signed(-828, 32), to_signed(-856, 32), to_signed(828, 32),
     to_signed(956, 32), to_signed(-583, 32), to_signed(-1162, 32), to_signed(0, 32), to_signed(1138, 32),
     to_signed(828, 32), to_signed(-410, 32), to_signed(-1189, 32), to_signed(-856, 32), to_signed(152, 32),
     to_signed(1001, 32), to_signed(1189, 32), to_signed(742, 32), to_signed(0, 32), to_signed(-680, 32),
     to_signed(-1095, 32), to_signed(-1209, 32), to_signed(-1095, 32), to_signed(-856, 32), to_signed(-583, 32),
     to_signed(-338, 32), to_signed(-152, 32), to_signed(-38, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32));  -- sfix32 [512]

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL count_step                       : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count_from                       : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL HDL_Counter_out1                 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL need_to_wrap                     : std_logic;
  SIGNAL count_value                      : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Direct_Lookup_Table_n_D_out1     : signed(31 DOWNTO 0);  -- int32
  SIGNAL Direct_Lookup_Table_n_D_1_out1   : signed(31 DOWNTO 0);  -- int32
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL IFFT_out1_re                     : std_logic_vector(40 DOWNTO 0);  -- ufix41
  SIGNAL IFFT_out1_im                     : std_logic_vector(40 DOWNTO 0);  -- ufix41
  SIGNAL IFFT_out1_re_signed              : signed(40 DOWNTO 0);  -- sfix41
  SIGNAL IFFT_out1_im_signed              : signed(40 DOWNTO 0);  -- sfix41
  SIGNAL Data_Type_Conversion_out1_re     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Data_Type_Conversion_out1_im     : signed(15 DOWNTO 0);  -- int16

BEGIN
  u_IFFT : IFFT
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn_re => std_logic_vector(Direct_Lookup_Table_n_D_out1),  -- int32
              dataIn_im => std_logic_vector(Direct_Lookup_Table_n_D_1_out1),  -- int32
              validIn => Constant_out1,
              dataOut_re => IFFT_out1_re,  -- sfix41
              dataOut_im => IFFT_out1_im  -- sfix41
              );

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 511
  count_step <= to_unsigned(16#001#, 9);

  count_from <= to_unsigned(16#000#, 9);

  enb <= clk_enable;

  count <= HDL_Counter_out1 + count_step;

  
  need_to_wrap <= '1' WHEN HDL_Counter_out1 = to_unsigned(16#1FF#, 9) ELSE
      '0';

  
  count_value <= count WHEN need_to_wrap = '0' ELSE
      count_from;

  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= to_unsigned(16#000#, 9);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        HDL_Counter_out1 <= count_value;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  Direct_Lookup_Table_n_D_out1 <= Direct_Lookup_Table_n_D_table_data(to_integer(HDL_Counter_out1));

  Direct_Lookup_Table_n_D_1_out1 <= Direct_Lookup_Table_n_D_1_table_data(to_integer(HDL_Counter_out1));

  Constant_out1 <= '1';

  IFFT_out1_re_signed <= signed(IFFT_out1_re);

  IFFT_out1_im_signed <= signed(IFFT_out1_im);

  Data_Type_Conversion_out1_re <= IFFT_out1_re_signed(15 DOWNTO 0);
  Data_Type_Conversion_out1_im <= IFFT_out1_im_signed(15 DOWNTO 0);

  Out1_re <= std_logic_vector(Data_Type_Conversion_out1_re);

  Out1_im <= std_logic_vector(Data_Type_Conversion_out1_im);

  ce_out <= clk_enable;

END rtl;

