-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\NewSignalGenerator\NewSignalGenerator.vhd
-- Created: 2026-05-04 21:14:01
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 3.25521e-09
-- Target subsystem base rate: 3.25521e-09
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        3.25521e-09
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1_re                       ce_out        3.25521e-09
-- Out1_im                       ce_out        3.25521e-09
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: NewSignalGenerator
-- Source Path: NewSignalGenerator
-- Hierarchy Level: 0
-- Model version: 1.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.NewSignalGenerator_pkg.ALL;

ENTITY NewSignalGenerator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out1_re                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        Out1_im                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END NewSignalGenerator;


ARCHITECTURE rtl OF NewSignalGenerator IS

  -- Component Declarations
  COMPONENT IFFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En20
          dataIn_im                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En20
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(40 DOWNTO 0);  -- sfix41_En20
          dataOut_im                      :   OUT   std_logic_vector(40 DOWNTO 0)  -- sfix41_En20
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : IFFT
    USE ENTITY work.IFFT(rtl);

  -- Constants
  CONSTANT LUT_Re_table_data              : vector_of_signed32(0 TO 511) := 
    (to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(1258291200, 32), to_signed(1257670309, 32),
     to_signed(1248369198, 32), to_signed(1208329094, 32), to_signed(1102648984, 32), to_signed(889746240, 32),
     to_signed(535754336, 32), to_signed(39523882, 32), to_signed(-535754336, 32), to_signed(-1040708208, 32),
     to_signed(-1258291200, 32), to_signed(-994245099, 32), to_signed(-235780259, 32), to_signed(707264568, 32),
     to_signed(1248369198, 32), to_signed(889746240, 32), to_signed(-235780259, 32), to_signed(-1183901992, 32),
     to_signed(-917254809, 32), to_signed(426230944, 32), to_signed(1258291200, 32), to_signed(351052054, 32),
     to_signed(-1102648984, 32), to_signed(-771215552, 32), to_signed(917254809, 32), to_signed(889746240, 32),
     to_signed(-917254809, 32), to_signed(-771215552, 32), to_signed(1102648984, 32), to_signed(351052054, 32),
     to_signed(-1258291200, 32), to_signed(426230944, 32), to_signed(917254809, 32), to_signed(-1183901992, 32),
     to_signed(235780259, 32), to_signed(889746240, 32), to_signed(-1248369198, 32), to_signed(707264568, 32),
     to_signed(235780259, 32), to_signed(-994245099, 32), to_signed(1258291200, 32), to_signed(-1040708208, 32),
     to_signed(535754336, 32), to_signed(39523882, 32), to_signed(-535754336, 32), to_signed(889746240, 32),
     to_signed(-1102648984, 32), to_signed(1208329094, 32), to_signed(-1248369198, 32), to_signed(1257670309, 32),
     to_signed(-1258291200, 32), to_signed(1257670309, 32), to_signed(-1248369198, 32), to_signed(1208329094, 32),
     to_signed(-1102648984, 32), to_signed(889746240, 32), to_signed(-535754336, 32), to_signed(39523882, 32),
     to_signed(535754336, 32), to_signed(-1040708208, 32), to_signed(1258291200, 32), to_signed(-994245099, 32),
     to_signed(235780259, 32), to_signed(707264568, 32), to_signed(-1248369198, 32), to_signed(889746240, 32),
     to_signed(235780259, 32), to_signed(-1183901992, 32), to_signed(917254809, 32), to_signed(426230944, 32),
     to_signed(-1258291200, 32), to_signed(351052054, 32), to_signed(1102648984, 32), to_signed(-771215552, 32),
     to_signed(-917254809, 32), to_signed(889746240, 32), to_signed(917254809, 32), to_signed(-771215552, 32),
     to_signed(-1102648984, 32), to_signed(351052054, 32), to_signed(1258291200, 32), to_signed(426230944, 32),
     to_signed(-917254809, 32), to_signed(-1183901992, 32), to_signed(-235780259, 32), to_signed(889746240, 32),
     to_signed(1248369198, 32), to_signed(707264568, 32), to_signed(-235780259, 32), to_signed(-994245099, 32),
     to_signed(-1258291200, 32), to_signed(-1040708208, 32), to_signed(-535754336, 32), to_signed(39523882, 32),
     to_signed(535754336, 32), to_signed(889746240, 32), to_signed(1102648984, 32), to_signed(1208329094, 32),
     to_signed(1248369198, 32), to_signed(1257670309, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(1257670309, 32),
     to_signed(1248369198, 32), to_signed(1208329094, 32), to_signed(1102648984, 32), to_signed(889746240, 32),
     to_signed(535754336, 32), to_signed(39523882, 32), to_signed(-535754336, 32), to_signed(-1040708208, 32),
     to_signed(-1258291200, 32), to_signed(-994245099, 32), to_signed(-235780259, 32), to_signed(707264568, 32),
     to_signed(1248369198, 32), to_signed(889746240, 32), to_signed(-235780259, 32), to_signed(-1183901992, 32),
     to_signed(-917254809, 32), to_signed(426230944, 32), to_signed(1258291200, 32), to_signed(351052054, 32),
     to_signed(-1102648984, 32), to_signed(-771215552, 32), to_signed(917254809, 32), to_signed(889746240, 32),
     to_signed(-917254809, 32), to_signed(-771215552, 32), to_signed(1102648984, 32), to_signed(351052054, 32),
     to_signed(-1258291200, 32), to_signed(426230944, 32), to_signed(917254809, 32), to_signed(-1183901992, 32),
     to_signed(235780259, 32), to_signed(889746240, 32), to_signed(-1248369198, 32), to_signed(707264568, 32),
     to_signed(235780259, 32), to_signed(-994245099, 32), to_signed(1258291200, 32), to_signed(-1040708208, 32),
     to_signed(535754336, 32), to_signed(39523882, 32), to_signed(-535754336, 32), to_signed(889746240, 32),
     to_signed(-1102648984, 32), to_signed(1208329094, 32), to_signed(-1248369198, 32), to_signed(1257670309, 32),
     to_signed(-1258291200, 32), to_signed(1257670309, 32), to_signed(-1248369198, 32), to_signed(1208329094, 32),
     to_signed(-1102648984, 32), to_signed(889746240, 32), to_signed(-535754336, 32), to_signed(39523882, 32),
     to_signed(535754336, 32), to_signed(-1040708208, 32), to_signed(1258291200, 32), to_signed(-994245099, 32),
     to_signed(235780259, 32), to_signed(707264568, 32), to_signed(-1248369198, 32), to_signed(889746240, 32),
     to_signed(235780259, 32), to_signed(-1183901992, 32), to_signed(917254809, 32), to_signed(426230944, 32),
     to_signed(-1258291200, 32), to_signed(351052054, 32), to_signed(1102648984, 32), to_signed(-771215552, 32),
     to_signed(-917254809, 32), to_signed(889746240, 32), to_signed(917254809, 32), to_signed(-771215552, 32),
     to_signed(-1102648984, 32), to_signed(351052054, 32), to_signed(1258291200, 32), to_signed(426230944, 32),
     to_signed(-917254809, 32), to_signed(-1183901992, 32), to_signed(-235780259, 32), to_signed(889746240, 32),
     to_signed(1248369198, 32), to_signed(707264568, 32), to_signed(-235780259, 32), to_signed(-994245099, 32),
     to_signed(-1258291200, 32), to_signed(-1040708208, 32), to_signed(-535754336, 32), to_signed(39523882, 32),
     to_signed(535754336, 32), to_signed(889746240, 32), to_signed(1102648984, 32), to_signed(1208329094, 32),
     to_signed(1248369198, 32), to_signed(1257670309, 32), to_signed(1258291200, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32));  -- sfix32 [512]
  CONSTANT LUT_Im_table_data              : vector_of_signed32(0 TO 511) := 
    (to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(39523882, 32),
     to_signed(157705705, 32), to_signed(351052054, 32), to_signed(606186409, 32), to_signed(889746240, 32),
     to_signed(1138535918, 32), to_signed(1257670309, 32), to_signed(1138535918, 32), to_signed(707264568, 32),
     to_signed(0, 32), to_signed(-771215552, 32), to_signed(-1236003403, 32), to_signed(-1040708208, 32),
     to_signed(-157705705, 32), to_signed(889746240, 32), to_signed(1236003403, 32), to_signed(426230944, 32),
     to_signed(-861359599, 32), to_signed(-1183901992, 32), to_signed(0, 32), to_signed(1208329094, 32),
     to_signed(606186409, 32), to_signed(-994245099, 32), to_signed(-861359599, 32), to_signed(889746240, 32),
     to_signed(861359599, 32), to_signed(-994245099, 32), to_signed(-606186409, 32), to_signed(1208329094, 32),
     to_signed(0, 32), to_signed(-1183901992, 32), to_signed(861359599, 32), to_signed(426230944, 32),
     to_signed(-1236003403, 32), to_signed(889746240, 32), to_signed(157705705, 32), to_signed(-1040708208, 32),
     to_signed(1236003403, 32), to_signed(-771215552, 32), to_signed(0, 32), to_signed(707264568, 32),
     to_signed(-1138535918, 32), to_signed(1257670309, 32), to_signed(-1138535918, 32), to_signed(889746240, 32),
     to_signed(-606186409, 32), to_signed(351052054, 32), to_signed(-157705705, 32), to_signed(39523882, 32),
     to_signed(0, 32), to_signed(39523882, 32), to_signed(-157705705, 32), to_signed(351052054, 32),
     to_signed(-606186409, 32), to_signed(889746240, 32), to_signed(-1138535918, 32), to_signed(1257670309, 32),
     to_signed(-1138535918, 32), to_signed(707264568, 32), to_signed(0, 32), to_signed(-771215552, 32),
     to_signed(1236003403, 32), to_signed(-1040708208, 32), to_signed(157705705, 32), to_signed(889746240, 32),
     to_signed(-1236003403, 32), to_signed(426230944, 32), to_signed(861359599, 32), to_signed(-1183901992, 32),
     to_signed(0, 32), to_signed(1208329094, 32), to_signed(-606186409, 32), to_signed(-994245099, 32),
     to_signed(861359599, 32), to_signed(889746240, 32), to_signed(-861359599, 32), to_signed(-994245099, 32),
     to_signed(606186409, 32), to_signed(1208329094, 32), to_signed(0, 32), to_signed(-1183901992, 32),
     to_signed(-861359599, 32), to_signed(426230944, 32), to_signed(1236003403, 32), to_signed(889746240, 32),
     to_signed(-157705705, 32), to_signed(-1040708208, 32), to_signed(-1236003403, 32), to_signed(-771215552, 32),
     to_signed(0, 32), to_signed(707264568, 32), to_signed(1138535918, 32), to_signed(1257670309, 32),
     to_signed(1138535918, 32), to_signed(889746240, 32), to_signed(606186409, 32), to_signed(351052054, 32),
     to_signed(157705705, 32), to_signed(39523882, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(-39523882, 32),
     to_signed(-157705705, 32), to_signed(-351052054, 32), to_signed(-606186409, 32), to_signed(-889746240, 32),
     to_signed(-1138535918, 32), to_signed(-1257670309, 32), to_signed(-1138535918, 32),
     to_signed(-707264568, 32), to_signed(0, 32), to_signed(771215552, 32), to_signed(1236003403, 32),
     to_signed(1040708208, 32), to_signed(157705705, 32), to_signed(-889746240, 32), to_signed(-1236003403, 32),
     to_signed(-426230944, 32), to_signed(861359599, 32), to_signed(1183901992, 32), to_signed(0, 32),
     to_signed(-1208329094, 32), to_signed(-606186409, 32), to_signed(994245099, 32), to_signed(861359599, 32),
     to_signed(-889746240, 32), to_signed(-861359599, 32), to_signed(994245099, 32), to_signed(606186409, 32),
     to_signed(-1208329094, 32), to_signed(0, 32), to_signed(1183901992, 32), to_signed(-861359599, 32),
     to_signed(-426230944, 32), to_signed(1236003403, 32), to_signed(-889746240, 32), to_signed(-157705705, 32),
     to_signed(1040708208, 32), to_signed(-1236003403, 32), to_signed(771215552, 32), to_signed(0, 32),
     to_signed(-707264568, 32), to_signed(1138535918, 32), to_signed(-1257670309, 32), to_signed(1138535918, 32),
     to_signed(-889746240, 32), to_signed(606186409, 32), to_signed(-351052054, 32), to_signed(157705705, 32),
     to_signed(-39523882, 32), to_signed(0, 32), to_signed(-39523882, 32), to_signed(157705705, 32),
     to_signed(-351052054, 32), to_signed(606186409, 32), to_signed(-889746240, 32), to_signed(1138535918, 32),
     to_signed(-1257670309, 32), to_signed(1138535918, 32), to_signed(-707264568, 32), to_signed(0, 32),
     to_signed(771215552, 32), to_signed(-1236003403, 32), to_signed(1040708208, 32), to_signed(-157705705, 32),
     to_signed(-889746240, 32), to_signed(1236003403, 32), to_signed(-426230944, 32), to_signed(-861359599, 32),
     to_signed(1183901992, 32), to_signed(0, 32), to_signed(-1208329094, 32), to_signed(606186409, 32),
     to_signed(994245099, 32), to_signed(-861359599, 32), to_signed(-889746240, 32), to_signed(861359599, 32),
     to_signed(994245099, 32), to_signed(-606186409, 32), to_signed(-1208329094, 32), to_signed(0, 32),
     to_signed(1183901992, 32), to_signed(861359599, 32), to_signed(-426230944, 32), to_signed(-1236003403, 32),
     to_signed(-889746240, 32), to_signed(157705705, 32), to_signed(1040708208, 32), to_signed(1236003403, 32),
     to_signed(771215552, 32), to_signed(0, 32), to_signed(-707264568, 32), to_signed(-1138535918, 32),
     to_signed(-1257670309, 32), to_signed(-1138535918, 32), to_signed(-889746240, 32), to_signed(-606186409, 32),
     to_signed(-351052054, 32), to_signed(-157705705, 32), to_signed(-39523882, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32), to_signed(0, 32),
     to_signed(0, 32), to_signed(0, 32));  -- sfix32 [512]

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL count_step                       : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count_from                       : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL HDL_Counter_out1                 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL need_to_wrap                     : std_logic;
  SIGNAL count_value                      : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL LUT_Re_out1                      : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL LUT_Im_out1                      : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL IFFT_out1_re                     : std_logic_vector(40 DOWNTO 0);  -- ufix41
  SIGNAL IFFT_out1_im                     : std_logic_vector(40 DOWNTO 0);  -- ufix41
  SIGNAL IFFT_out1_re_signed              : signed(40 DOWNTO 0);  -- sfix41_En20
  SIGNAL IFFT_out1_im_signed              : signed(40 DOWNTO 0);  -- sfix41_En20
  SIGNAL Data_Type_Conversion_out1_re     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Data_Type_Conversion_out1_im     : signed(15 DOWNTO 0);  -- int16

BEGIN
  u_IFFT : IFFT
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn_re => std_logic_vector(LUT_Re_out1),  -- sfix32_En20
              dataIn_im => std_logic_vector(LUT_Im_out1),  -- sfix32_En20
              validIn => Constant_out1,
              dataOut_re => IFFT_out1_re,  -- sfix41_En20
              dataOut_im => IFFT_out1_im  -- sfix41_En20
              );

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 511
  count_step <= to_unsigned(16#001#, 9);

  count_from <= to_unsigned(16#000#, 9);

  enb <= clk_enable;

  count <= HDL_Counter_out1 + count_step;

  
  need_to_wrap <= '1' WHEN HDL_Counter_out1 = to_unsigned(16#1FF#, 9) ELSE
      '0';

  
  count_value <= count WHEN need_to_wrap = '0' ELSE
      count_from;

  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= to_unsigned(16#000#, 9);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        HDL_Counter_out1 <= count_value;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  LUT_Re_out1 <= LUT_Re_table_data(to_integer(HDL_Counter_out1));

  LUT_Im_out1 <= LUT_Im_table_data(to_integer(HDL_Counter_out1));

  Constant_out1 <= '1';

  IFFT_out1_re_signed <= signed(IFFT_out1_re);

  IFFT_out1_im_signed <= signed(IFFT_out1_im);

  Data_Type_Conversion_out1_re <= IFFT_out1_re_signed(35 DOWNTO 20);
  Data_Type_Conversion_out1_im <= IFFT_out1_im_signed(35 DOWNTO 20);

  Out1_re <= std_logic_vector(Data_Type_Conversion_out1_re);

  Out1_im <= std_logic_vector(Data_Type_Conversion_out1_im);

  ce_out <= clk_enable;

END rtl;

